(function(){
  const SUPPLIES={water:{name:'瓶裝水',rarity:'common',basePrice:12,desc:'探索中罪人 HP ≤45% 時自動使用，回復 25 HP。'},potion:{name:'小型治療藥水',rarity:'uncommon',basePrice:30,desc:'瓶裝水不足且 HP ≤20% 時自動使用，回復 45 HP。'}};
  const GEAR_PRICES={'runner-boots':115,'field-vest':125,'survey-lens':130,'shock-baton':140,'field-kit':210};
  const AREA_SHOPS={'zone-1':{name:'封鎖線雜貨攤',flavor:'撤離區留下的臨時商販，價格最接近基準。',mult:1},'zone-2':{name:'維修層零件販子',flavor:'貨物多由維修通道回收，運送成本略高。',mult:1.08},'zone-3':{name:'研究棟回收櫃',flavor:'高危區物資有額外風險成本。',mult:1.18},'zone-4':{name:'黑區行腳商',flavor:'深入黑區的物流風險最高，但裝備種類也較多。',mult:1.30}};
  let mode='buy';
  const round=n=>Math.max(1,Math.round(n/5)*5),sid=()=>('S-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7));
  function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function createExplorationShop(area,names){ensureExplorationState();const info=AREA_SHOPS[area.id]||AREA_SHOPS['zone-1'],n=area.level>=8?3:area.level>=5?2:1;
    const stock=[{stockId:sid(),type:'supply',itemId:'water',name:SUPPLIES.water.name,desc:SUPPLIES.water.desc,rarity:'common',price:round(12*info.mult),qty:2+Math.floor(Math.random()*3)},{stockId:sid(),type:'supply',itemId:'potion',name:SUPPLIES.potion.name,desc:SUPPLIES.potion.desc,rarity:'uncommon',price:round(30*info.mult),qty:1+Math.floor(Math.random()*2)}];
    shuffle(Object.keys(FIELD_GEAR).filter(id=>!state.exploration.fieldGear.includes(id))).slice(0,n).forEach(function(id){const g=FIELD_GEAR[id];stock.push({stockId:sid(),type:'gear',itemId:id,name:g.name,desc:g.desc,rarity:g.rarity||'common',price:round((GEAR_PRICES[id]||140)*info.mult*(.95+Math.random()*.1)),qty:1})});
    const shop={id:'SHOP-'+Date.now(),areaId:area.id,name:info.name,flavor:info.flavor,openedAt:new Date().toISOString(),team:(names||[]).slice(0,2),stock:stock,purchases:[],sales:[]};state.exploration.activeShop=shop;mode='buy';return shop;
  }
  function refresh(){try{renderExplorationShop();renderBackpack();renderSinnerManagement();renderRpg();if(typeof forceRenderManagerProgress==='function')forceRenderManagerProgress()}catch(e){console.error(e)}}
  function buy(id){const shop=state.exploration.activeShop,item=(shop&&shop.stock||[]).find(x=>x.stockId===id);if(!item||item.qty<=0){toast('商品已售罄');return}const ef=equipmentEffects(),p=Math.max(1,Math.round(item.price*(1-(ef.shopDiscount||0))));if(state.rpg.gold<p){toast('金幣不足');return}if(item.type==='gear'&&state.exploration.fieldGear.includes(item.itemId)){toast('已持有這件探索裝備');return}state.rpg.gold-=p;item.qty--;if(item.type==='supply')state.rpg.consumables[item.itemId]=(state.rpg.consumables[item.itemId]||0)+1;else state.exploration.fieldGear.push(item.itemId);shop.purchases.push({name:item.name,price:p});state.rpg.rewardLog='商店購入：'+item.name+'\n支付 '+p+' 金幣。';saveLocal();refresh();toast('購入 '+item.name)}
  function sell(token){if(typeof sellInventoryToken!=='function'){toast('出售系統尚未載入');return}const r=sellInventoryToken(token);if(!r.ok){toast(r.message);return}const shop=state.exploration.activeShop;shop.sales=shop.sales||[];shop.sales.push({name:r.item.name,price:r.gold});saveLocal();refresh();toast('出售 '+r.item.name+'，獲得 '+r.gold+' G')}
  function rr(v){return typeof itemRarity==='function'?itemRarity(v):{className:'rarity-common',label:'一般'}}
  function buyHtml(shop){const ef=equipmentEffects();return '<div class="shop-stock">'+shop.stock.map(function(i){const r=rr(i.rarity),p=Math.max(1,Math.round(i.price*(1-(ef.shopDiscount||0)))),sold=i.qty<=0,ok=!sold&&state.rpg.gold>=p;return '<article class="shop-item '+r.className+' '+(sold?'soldout':'')+'"><div class="shop-item-head"><div><div class="shop-item-name">'+esc(i.name)+'</div><div class="shop-item-kind">'+(i.type==='gear'?'EQUIPMENT':'SUPPLY')+' · '+r.label+'</div></div><div class="shop-price">'+p+' G</div></div><div class="shop-item-desc">'+esc(i.desc)+'</div><div class="shop-item-foot"><span class="shop-stock-count">STOCK / '+i.qty+'</span><button class="wood shop-buy" data-shop-buy="'+esc(i.stockId)+'" '+(ok?'':'disabled')+'>'+(sold?'售罄':ok?'購買':'金幣不足')+'</button></div></article>'}).join('')+'</div>'}
  function sellHtml(){const arr=typeof inventorySellables==='function'?inventorySellables():[];if(!arr.length)return '<div class="shop-empty">目前沒有可出售物品。</div>';return '<div class="shop-stock">'+arr.map(function(i){const r=rr(i.rarity);return '<article class="shop-item '+r.className+' '+(!i.canSell?'soldout':'')+'"><div class="shop-item-head"><div><div class="shop-item-name">'+esc(i.name)+'</div><div class="shop-item-kind">'+r.label+' · 庫存 '+i.qty+'</div></div><div class="shop-price">+'+i.price+' G</div></div><div class="shop-item-desc">'+(i.canSell?'每次出售 1 件／1 個。':esc(i.reason||'目前不可出售'))+'</div><div class="shop-item-foot"><span class="shop-stock-count">SELL VALUE</span><button class="wood shop-sell" data-shop-sell="'+esc(i.token)+'" '+(i.canSell?'':'disabled')+'>'+(i.canSell?'出售':'不可出售')+'</button></div></article>'}).join('')+'</div>'}
  function renderExplorationShop(){const m=document.getElementById('explorationShop');if(!m)return;ensureExplorationState();const shop=state.exploration.activeShop;if(!shop){m.hidden=true;m.innerHTML='';return}m.hidden=false;m.innerHTML='<div class="shop-head"><div><div class="shop-kicker">RANDOM EVENT // FIELD SHOP</div><div class="shop-title">'+esc(shop.name)+'</div></div><div class="shop-wallet">CURRENT GOLD<b>'+state.rpg.gold+' G</b></div></div><div class="shop-flavor">'+esc(shop.flavor)+'</div><div class="shop-mode-switch"><button data-shop-mode="buy" class="'+(mode==='buy'?'active':'')+'">購買</button><button data-shop-mode="sell" class="'+(mode==='sell'?'active':'')+'">出售</button></div>'+(mode==='buy'?buyHtml(shop):sellHtml())+'<div class="shop-note">購入價格依區域風險調整；出售價格依物品類型與稀有度計算。已配置或已裝備的裝備不可出售。</div>';m.querySelectorAll('[data-shop-mode]').forEach(x=>x.onclick=()=>{mode=x.dataset.shopMode;renderExplorationShop()});m.querySelectorAll('[data-shop-buy]').forEach(x=>x.onclick=()=>buy(x.dataset.shopBuy));m.querySelectorAll('[data-shop-sell]').forEach(x=>x.onclick=()=>sell(x.dataset.shopSell))}
  window.createExplorationShop=createExplorationShop;window.buyExplorationShopItem=buy;window.renderExplorationShop=renderExplorationShop;document.addEventListener('DOMContentLoaded',()=>setTimeout(renderExplorationShop,0));window.addEventListener('pageshow',()=>setTimeout(renderExplorationShop,0));
})();